-- v70: 담당부서 직제 명칭 정비 (사무처 및 5개 국 체계)
-- 내부 저장값은 `사무처 - ○○국`, 화면 표시값은 `사무처(○○국)`을 사용합니다.

UPDATE system_users SET department = CASE
  WHEN TRIM(department) IN ('사무국','사무처') THEN '사무처'
  WHEN TRIM(department) IN ('재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국') THEN '사무처 - ' || TRIM(department)
  WHEN TRIM(department) IN ('재정·회계','사무국 - 재정·회계','사무처 - 재정·회계','사무국(재정·회계)','사무처(재정·회계)') THEN '사무처 - 재정국'
  WHEN TRIM(department) IN ('준법·윤리','사무국 - 준법·윤리','사무처 - 준법·윤리','사무국(준법·윤리)','사무처(준법·윤리)') THEN '사무처 - 준법윤리국'
  WHEN TRIM(department) IN ('문화·홍보','사무국 - 문화·홍보','사무처 - 문화·홍보','사무국(문화·홍보)','사무처(문화·홍보)') THEN '사무처 - 문화홍보국'
  WHEN TRIM(department) IN ('대외협력·사회공헌','사무국 - 대외협력·사회공헌','사무처 - 대외협력·사회공헌','사무국(대외협력·사회공헌)','사무처(대외협력·사회공헌)') THEN CASE WHEN COALESCE(position,'') LIKE '%사회공헌%' THEN '사무처 - 사회공헌국' ELSE '사무처 - 국제교류국' END
  ELSE REPLACE(department,'사무국','사무처') END
WHERE department IS NOT NULL AND (department LIKE '%사무국%' OR TRIM(department) IN ('재정·회계','준법·윤리','대외협력·사회공헌','문화·홍보','재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국'));

-- 직책정보가 없는 과거 문서·대장은 기존 통합 `대외협력·사회공헌` 값을 국제교류국으로 이관합니다.
UPDATE documents SET department = CASE WHEN department IS NULL OR TRIM(department)='' THEN department WHEN TRIM(department) IN ('사무국','사무처') THEN '사무처' WHEN TRIM(department) IN ('재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국') THEN '사무처 - ' || TRIM(department) WHEN TRIM(department) IN ('재정·회계','사무국 - 재정·회계','사무처 - 재정·회계','사무국(재정·회계)','사무처(재정·회계)') THEN '사무처 - 재정국' WHEN TRIM(department) IN ('준법·윤리','사무국 - 준법·윤리','사무처 - 준법·윤리','사무국(준법·윤리)','사무처(준법·윤리)') THEN '사무처 - 준법윤리국' WHEN TRIM(department) IN ('문화·홍보','사무국 - 문화·홍보','사무처 - 문화·홍보','사무국(문화·홍보)','사무처(문화·홍보)') THEN '사무처 - 문화홍보국' WHEN TRIM(department) IN ('대외협력·사회공헌','사무국 - 대외협력·사회공헌','사무처 - 대외협력·사회공헌','사무국(대외협력·사회공헌)','사무처(대외협력·사회공헌)') THEN '사무처 - 국제교류국' ELSE REPLACE(department,'사무국','사무처') END WHERE department LIKE '%사무국%' OR TRIM(department) IN ('재정·회계','준법·윤리','대외협력·사회공헌','문화·홍보','재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국');
UPDATE received_documents SET department = CASE WHEN department IS NULL OR TRIM(department)='' THEN department WHEN TRIM(department) IN ('사무국','사무처') THEN '사무처' WHEN TRIM(department) IN ('재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국') THEN '사무처 - ' || TRIM(department) WHEN TRIM(department) IN ('재정·회계','사무국 - 재정·회계','사무처 - 재정·회계','사무국(재정·회계)','사무처(재정·회계)') THEN '사무처 - 재정국' WHEN TRIM(department) IN ('준법·윤리','사무국 - 준법·윤리','사무처 - 준법·윤리','사무국(준법·윤리)','사무처(준법·윤리)') THEN '사무처 - 준법윤리국' WHEN TRIM(department) IN ('문화·홍보','사무국 - 문화·홍보','사무처 - 문화·홍보','사무국(문화·홍보)','사무처(문화·홍보)') THEN '사무처 - 문화홍보국' WHEN TRIM(department) IN ('대외협력·사회공헌','사무국 - 대외협력·사회공헌','사무처 - 대외협력·사회공헌','사무국(대외협력·사회공헌)','사무처(대외협력·사회공헌)') THEN '사무처 - 국제교류국' ELSE REPLACE(department,'사무국','사무처') END WHERE department LIKE '%사무국%' OR TRIM(department) IN ('재정·회계','준법·윤리','대외협력·사회공헌','문화·홍보','재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국');
UPDATE management_registers SET applicant_department = CASE WHEN applicant_department IS NULL OR TRIM(applicant_department)='' THEN applicant_department WHEN TRIM(applicant_department) IN ('사무국','사무처') THEN '사무처' WHEN TRIM(applicant_department) IN ('재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국') THEN '사무처 - ' || TRIM(applicant_department) WHEN TRIM(applicant_department) IN ('재정·회계','사무국 - 재정·회계','사무처 - 재정·회계','사무국(재정·회계)','사무처(재정·회계)') THEN '사무처 - 재정국' WHEN TRIM(applicant_department) IN ('준법·윤리','사무국 - 준법·윤리','사무처 - 준법·윤리','사무국(준법·윤리)','사무처(준법·윤리)') THEN '사무처 - 준법윤리국' WHEN TRIM(applicant_department) IN ('문화·홍보','사무국 - 문화·홍보','사무처 - 문화·홍보','사무국(문화·홍보)','사무처(문화·홍보)') THEN '사무처 - 문화홍보국' WHEN TRIM(applicant_department) IN ('대외협력·사회공헌','사무국 - 대외협력·사회공헌','사무처 - 대외협력·사회공헌','사무국(대외협력·사회공헌)','사무처(대외협력·사회공헌)') THEN '사무처 - 국제교류국' ELSE REPLACE(applicant_department,'사무국','사무처') END WHERE applicant_department LIKE '%사무국%' OR TRIM(applicant_department) IN ('재정·회계','준법·윤리','대외협력·사회공헌','문화·홍보','재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국');
UPDATE employment_certificates SET department = CASE WHEN department IS NULL OR TRIM(department)='' THEN department WHEN TRIM(department) IN ('사무국','사무처') THEN '사무처' WHEN TRIM(department) IN ('재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국') THEN '사무처 - ' || TRIM(department) WHEN TRIM(department) IN ('재정·회계','사무국 - 재정·회계','사무처 - 재정·회계','사무국(재정·회계)','사무처(재정·회계)') THEN '사무처 - 재정국' WHEN TRIM(department) IN ('준법·윤리','사무국 - 준법·윤리','사무처 - 준법·윤리','사무국(준법·윤리)','사무처(준법·윤리)') THEN '사무처 - 준법윤리국' WHEN TRIM(department) IN ('문화·홍보','사무국 - 문화·홍보','사무처 - 문화·홍보','사무국(문화·홍보)','사무처(문화·홍보)') THEN '사무처 - 문화홍보국' WHEN TRIM(department) IN ('대외협력·사회공헌','사무국 - 대외협력·사회공헌','사무처 - 대외협력·사회공헌','사무국(대외협력·사회공헌)','사무처(대외협력·사회공헌)') THEN '사무처 - 국제교류국' ELSE REPLACE(department,'사무국','사무처') END WHERE department LIKE '%사무국%' OR TRIM(department) IN ('재정·회계','준법·윤리','대외협력·사회공헌','문화·홍보','재정국','준법윤리국','국제교류국','문화홍보국','사회공헌국');
