import { authenticateSession, clean, ensureTables, json, normalizeDepartmentValue, makeDocumentNumber, randomHex } from '../../_shared/helpers';
import { cleanAccountingText, ensureAccountingTables, hasAccountingAccess, isAccountingManager, isPeriodClosed, monthlySummaryStatement, nextAccountingNumber, parseMoney } from '../../_shared/accounting';
import { validateDimensions } from '../../_shared/accounting-special';
import { accountingEventStatement, ensureAccountingIntegrationSchema, processAccountingOutbox } from '../../_shared/accounting-integration';
import { budgetVersionStatement, ensureAccountingOperationsTables, getBudgetCommittedAmount, getReconciliationBlockers } from '../../_shared/accounting-operations';

interface Env { DB:D1Database; ACCOUNTING_DB:D1Database; }
type Payload=Record<string,unknown>&{token?:string;action?:string};
type UserRow={id:string;name:string;position:string|null;can_approve:number;active:number};
type ApprovalLine={lineType:'협조'|'검토'|'결재'|'전결';userId:string;userName:string;userPosition:string|null};
const statusForLineType=(type:ApprovalLine['lineType'])=>type==='협조'?'협조대기':type==='검토'?'검토대기':type==='전결'?'전결대기':'결재대기';
const listIds=(raw:unknown)=>Array.isArray(raw)?raw.map((v)=>clean(v,60)).filter((v,i,a)=>v&&a.indexOf(v)===i):[];
const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value);
const auditStatement=(db:D1Database,action:string,type:string,id:string,userId:string,userName:string,detail:unknown,now:string)=>db.prepare(`INSERT INTO accounting_audit_logs (id,action,entity_type,entity_id,actor_user_id,actor_name,detail_json,created_at) VALUES (?,?,?,?,?,?,?,?)`).bind(`LOG-${randomHex(20)}`,action,type,id,userId,userName,JSON.stringify(detail||{}),now);

export const onRequestPost:PagesFunction<Env>=async({request,env})=>{
  if(!env.DB||!env.ACCOUNTING_DB)return json({ok:false,message:'전자문서 DB 또는 회계 전용 DB가 연결되지 않았습니다.'},500);
  let payload:Payload;try{payload=await request.json()}catch{return json({ok:false,message:'요청 형식이 올바르지 않습니다.'},400)}
  await ensureTables(env.DB);
  const auth=await authenticateSession(env.DB,clean(payload.token,200));if(!auth.ok)return json({ok:false,message:auth.message},auth.status);
  if(!hasAccountingAccess(auth.user))return json({ok:false,message:'종단 회계관리 접속 권한이 없습니다. 관리자에게 회계권한 부여를 요청해 주세요.'},403);
  await ensureAccountingTables(env.ACCOUNTING_DB);
  await ensureAccountingOperationsTables(env.ACCOUNTING_DB);
  const db=env.ACCOUNTING_DB,me=auth.user,action=clean(payload.action,50),manager=isAccountingManager(me);
  if(me.role==='audit')return json({ok:false,message:'감사 계정은 회계자료를 열람할 수 있지만 등록·수정할 수 없습니다.'},403);
  try{
    if(action==='save-fiscal-year'){
      if(!manager)return json({ok:false,message:'회계연도 설정 권한이 없습니다.'},403);const year=Number(payload.year);if(!Number.isInteger(year)||year<2000||year>2200)return json({ok:false,message:'회계연도를 확인해 주세요.'},400);const now=new Date().toISOString();
      await db.batch([db.prepare(`INSERT INTO accounting_fiscal_years (year,name,start_date,end_date,base_currency,status,created_by,created_at) VALUES (?,?,?,?,?,'open',?,?) ON CONFLICT(year) DO UPDATE SET name=excluded.name,start_date=excluded.start_date,end_date=excluded.end_date,base_currency=excluded.base_currency`).bind(year,clean(payload.name,80)||`${year} 회계연도`,clean(payload.startDate,10)||`${year}-01-01`,clean(payload.endDate,10)||`${year}-12-31`,clean(payload.currency,10)||'KRW',me.name,now),auditStatement(db,'save','fiscal-year',String(year),me.id,me.name,payload,now)]);return json({ok:true,message:'회계연도를 저장했습니다.'});
    }
    if(action==='save-account'){
      if(!manager)return json({ok:false,message:'계정과목 관리 권한이 없습니다.'},403);const code=clean(payload.code,20).replace(/[^0-9A-Za-z_-]/g,''),name=clean(payload.name,80),type=clean(payload.accountType,20),side=clean(payload.normalSide,10);if(!code||!name||!['asset','liability','equity','revenue','expense'].includes(type)||!['debit','credit'].includes(side))return json({ok:false,message:'계정과목 정보를 정확히 입력해 주세요.'},400);const existing=await db.prepare(`SELECT system_account FROM accounting_accounts WHERE code=?`).bind(code).first<{system_account:number}>();if(existing?.system_account)return json({ok:false,message:'기본 계정과목은 코드·유형을 변경할 수 없습니다. 별도 하위 계정과목을 추가해 주세요.'},400);const now=new Date().toISOString();
      await db.batch([db.prepare(`INSERT INTO accounting_accounts (code,name,account_type,normal_side,parent_code,active,system_account,created_at,updated_at) VALUES (?,?,?,?,?,1,0,?,?) ON CONFLICT(code) DO UPDATE SET name=excluded.name,account_type=excluded.account_type,normal_side=excluded.normal_side,parent_code=excluded.parent_code,active=1,updated_at=excluded.updated_at`).bind(code,name,type,side,clean(payload.parentCode,20)||null,now,now),auditStatement(db,'save','account',code,me.id,me.name,{code,name,type,side},now)]);return json({ok:true,message:'계정과목을 저장했습니다.'});
    }
    if(action==='save-budget'){
      if(!manager)return json({ok:false,message:'예산 편성 권한이 없습니다.'},403);const year=Number(payload.year),accountCode=clean(payload.accountCode,20),department=normalizeDepartmentValue(payload.department, me.position || ''),project=clean(payload.project,100);if(!Number.isInteger(year)||!accountCode)return json({ok:false,message:'회계연도와 예산 계정과목을 선택해 주세요.'},400);const dimensions=await validateDimensions(db,payload);const account=await db.prepare(`SELECT account_type FROM accounting_accounts WHERE code=? AND active=1`).bind(accountCode).first<{account_type:string}>();if(!account||account.account_type!=='expense')return json({ok:false,message:'예산은 지출 계정과목으로 편성해 주세요.'},400);const now=new Date().toISOString(),id=`BUD-${year}-${randomHex(14)}`,amounts={original:parseMoney(payload.originalAmount),supplementary:parseMoney(payload.supplementaryAmount),transferIn:parseMoney(payload.transferIn),transferOut:parseMoney(payload.transferOut)};if(Object.values(amounts).some((v)=>v<0))return json({ok:false,message:'예산 금액은 0원 이상으로 입력해 주세요.'},400);
      const existing=await db.prepare(`SELECT * FROM accounting_budget_plans WHERE fiscal_year=? AND book_type_code=? AND entity_id=? AND fund_id=? AND department=? AND project=? AND account_code=?`).bind(year,dimensions.bookTypeCode,dimensions.entityId,dimensions.fundId,department,project,accountCode).first<any>();
      if(existing){
        const changed=Number(existing.original_amount)!==amounts.original||Number(existing.supplementary_amount)!==amounts.supplementary||Number(existing.transfer_in)!==amounts.transferIn||Number(existing.transfer_out)!==amounts.transferOut;
        if(changed)return json({ok:false,message:'확정된 예산금액은 직접 덮어쓸 수 없습니다. 실무관리의 예산 변경요청에서 추경·전용·감액 절차를 이용해 주세요.',budgetChangeRequired:true},409);
        await db.batch([db.prepare(`UPDATE accounting_budget_plans SET memo=?,updated_at=? WHERE id=?`).bind(clean(payload.memo,1000)||null,now,existing.id),auditStatement(db,'update-memo','budget',existing.id,me.id,me.name,{memo:clean(payload.memo,1000)},now)]);
        return json({ok:true,message:'예산 비고를 저장했습니다.'});
      }
      const budget={id,original_amount:amounts.original,supplementary_amount:amounts.supplementary,transfer_in:amounts.transferIn,transfer_out:amounts.transferOut,memo:clean(payload.memo,1000)||null};
      await db.batch([
        db.prepare(`INSERT INTO accounting_budget_plans (id,fiscal_year,book_type_code,entity_id,fund_id,department,project,account_code,original_amount,supplementary_amount,transfer_in,transfer_out,memo,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,year,dimensions.bookTypeCode,dimensions.entityId,dimensions.fundId,department,project,accountCode,amounts.original,amounts.supplementary,amounts.transferIn,amounts.transferOut,budget.memo,me.name,now,now),
        budgetVersionStatement(db,budget,1,'initial',null,me.name,now),
        auditStatement(db,'create','budget',id,me.id,me.name,{...amounts,...dimensions},now),
      ]);return json({ok:true,message:'본예산을 편성하고 최초 버전을 확정했습니다.'});
    }
    if(action==='create-resolution'){
      await ensureAccountingIntegrationSchema(env.DB);
      const type=clean(payload.resolutionType,20);if(!['income','expense'].includes(type))return json({ok:false,message:'수입 또는 지출 결의 구분을 선택해 주세요.'},400);const date=clean(payload.resolutionDate,10);if(!validDate(date))return json({ok:false,message:'결의일자를 확인해 주세요.'},400);if(await isPeriodClosed(db,date))return json({ok:false,message:'해당 회계기간은 마감되어 결의서를 작성할 수 없습니다.'},400);const payment=clean(payload.paymentMethod,40),isCorporateCard=payment==='법인카드';if(isCorporateCard&&type!=='expense')return json({ok:false,message:'법인카드 지급은 지출결의에서만 사용할 수 있습니다.'},400);const year=Number(date.slice(0,4)),title=clean(payload.title,200),amount=parseMoney(payload.amount),accountCode=clean(payload.accountCode,20),settlement=clean(payload.settlementAccountCode,20)||(isCorporateCard?'2110':'1120');if(!title||amount<=0||!accountCode)return json({ok:false,message:'제목·금액·계정과목을 정확히 입력해 주세요.'},400);
      const accounts=await db.prepare(`SELECT code,name,account_type,normal_side FROM accounting_accounts WHERE code IN (?,?) AND active=1`).bind(accountCode,settlement).all<{code:string;name:string;account_type:string;normal_side:string}>();
      const accountRows=accounts.results||[],accountTypeMap=new Map(accountRows.map((a)=>[a.code,a.account_type])),accountNormalMap=new Map(accountRows.map((a)=>[a.code,a.normal_side])),accountNameMap=new Map(accountRows.map((a)=>[a.code,a.name]));
      if(accountTypeMap.get(accountCode)!==(type==='income'?'revenue':'expense'))return json({ok:false,message:type==='income'?'수입 계정과목을 선택해 주세요.':'지출 계정과목을 선택해 주세요.'},400);if(isCorporateCard){if(accountTypeMap.get(settlement)!=='liability'||accountNormalMap.get(settlement)!=='credit')return json({ok:false,message:'법인카드 지급은 법인카드미지급금 등 부채·대변 계정을 선택해 주세요.'},400)}else if(accountTypeMap.get(settlement)!=='asset'||accountNormalMap.get(settlement)!=='debit')return json({ok:false,message:'입·출금 계정은 현금·예금 등 자산·차변 계정으로 선택해 주세요.'},400);
      const dimensions=await validateDimensions(db,payload);
      const [bookResult,entityResult,fundResult]=await db.batch([
        db.prepare(`SELECT name FROM accounting_book_types WHERE code=?`).bind(dimensions.bookTypeCode),
        db.prepare(`SELECT name FROM accounting_entities WHERE id=?`).bind(dimensions.entityId),
        dimensions.fundId?db.prepare(`SELECT name FROM accounting_funds WHERE id=?`).bind(dimensions.fundId):db.prepare(`SELECT '해당 없음' AS name`),
      ]);
      const bookTypeName=String((bookResult.results?.[0] as any)?.name||dimensions.bookTypeCode),entityName=String((entityResult.results?.[0] as any)?.name||dimensions.entityId),fundName=String((fundResult.results?.[0] as any)?.name||(dimensions.fundId||'해당 없음'));
      const accountDisplay=`${accountCode} ${accountNameMap.get(accountCode)||''}`.trim(),settlementDisplay=`${settlement} ${accountNameMap.get(settlement)||''}`.trim();
      const department=normalizeDepartmentValue(payload.department, me.position || '')||normalizeDepartmentValue(me.department, me.position || '')||'',project=clean(payload.project,100),counterparty=clean(payload.counterparty,120);
      let approvedBudgetException:any=null;
      if(type==='expense'){
        const budget=await db.prepare(`SELECT *,(original_amount+supplementary_amount+transfer_in-transfer_out) AS revised FROM accounting_budget_plans WHERE fiscal_year=? AND book_type_code=? AND entity_id=? AND fund_id=? AND department=? AND project=? AND account_code=?`).bind(year,dimensions.bookTypeCode,dimensions.entityId,dimensions.fundId,department,project,accountCode).first<any>();
        if(budget){
          const used=await db.prepare(`SELECT COALESCE(SUM(debit_total-credit_total),0) AS used FROM accounting_monthly_summary WHERE fiscal_year=? AND account_code=? AND department=? AND project=? AND book_type_code=? AND entity_id=? AND fund_id=?`).bind(year,accountCode,department,project,dimensions.bookTypeCode,dimensions.entityId,dimensions.fundId).first<{used:number}>();
          const committed=await getBudgetCommittedAmount(db,budget),available=Number(budget.revised||0)-Number(used?.used||0)-committed;
          if(amount>available){
            const exceptionId=clean(payload.budgetExceptionId,100);
            approvedBudgetException=exceptionId?await db.prepare(`SELECT * FROM accounting_budget_change_requests WHERE id=? AND change_type='over_budget_exception' AND status='approved' AND target_budget_id=? AND requested_amount>=? AND consumed_by_resolution_id IS NULL AND (valid_until IS NULL OR valid_until='' OR valid_until>=?)`).bind(exceptionId,budget.id,amount-available,date).first<any>():null;
            if(!approvedBudgetException)return json({ok:false,message:`약정액을 반영한 가용예산(${available.toLocaleString('ko-KR')}원)을 초과합니다. 실무관리에서 초과집행 예외승인을 먼저 받은 뒤 해당 승인번호를 선택해 주세요.`,budgetWarning:true,available,committed,exceptionRequired:true},400);
          }
        }
      }
      const approverId=clean(payload.approverUserId,60);if(!approverId)return json({ok:false,message:'최종 결재자를 선택해 주세요.'},400);const cooperatorIds=listIds(payload.cooperatorUserIds),reviewerIds=listIds(payload.reviewerUserIds),allIds=[...cooperatorIds,...reviewerIds,approverId];if(new Set(allIds).size!==allIds.length)return json({ok:false,message:'협조자·검토자·결재자는 서로 다르게 지정해 주세요.'},400);const users=await env.DB.prepare(`SELECT CAST(id AS TEXT) AS id,name,position,can_approve,active FROM system_users WHERE CAST(id AS TEXT) IN (${allIds.map(()=>'?').join(',')})`).bind(...allIds).all<UserRow>();const userMap=new Map((users.results||[]).map((u)=>[u.id,u]));if(allIds.some((id)=>!userMap.get(id)?.active))return json({ok:false,message:'선택한 결재선에 사용할 수 없는 계정이 있습니다.'},400);const approver=userMap.get(approverId)!;if(!approver.can_approve)return json({ok:false,message:'최종 결재자에게 결재권이 없습니다.'},400);
      const lines:ApprovalLine[]=[];cooperatorIds.forEach((id)=>{const u=userMap.get(id)!;lines.push({lineType:'협조',userId:id,userName:u.name,userPosition:u.position})});reviewerIds.forEach((id)=>{const u=userMap.get(id)!;lines.push({lineType:'검토',userId:id,userName:u.name,userPosition:u.position})});lines.push({lineType:'결재',userId:approver.id,userName:approver.name,userPosition:approver.position});const selfImmediate=lines.length===1&&approver.id===me.id;
      const now=new Date(),nowIso=now.toISOString(),resolutionId=`RES-${randomHex(24)}`,resolutionNo=await nextAccountingNumber(db,type==='income'?'resolution-income':'resolution-expense',year),documentId=await makeDocumentNumber(env.DB,now),status=selfImmediate?'승인':statusForLineType(lines[0].lineType),memo=clean(payload.memo,2000),typeLabel=type==='income'?'수입결의':'지출결의';
      const amountDisplay=`${amount.toLocaleString('ko-KR')}원`;
      const body=`1. 결의번호: ${resolutionNo}\n2. 결의일자: ${date}\n3. 결의구분: ${typeLabel}\n4. 회계구분: ${bookTypeName}\n5. 회계조직: ${entityName}\n6. 재원: ${fundName}\n7. 계정과목: ${accountDisplay}\n8. 금액: ${amountDisplay}\n9. 거래처·납부자: ${counterparty||'-'}\n10. 담당부서 / 사업: ${department||'-'} / ${project||'-'}\n11. 입·출금계정: ${settlementDisplay}\n12. 지급·수납방법: ${payment||'-'}\n13. 비고\n${memo||'없음'}`;
      const formData={_accountingResolutionId:resolutionId,_accountingLabels:{resolutionNo,resolutionType:typeLabel,amount:amountDisplay,accountCode:accountDisplay,settlementAccountCode:settlementDisplay,bookTypeCode:bookTypeName,entityId:entityName,fundId:fundName},resolutionNo,resolutionType:type,amount:String(amount),accountCode,settlementAccountCode:settlement,bookTypeCode:dimensions.bookTypeCode,entityId:dimensions.entityId,fundId:dimensions.fundId};
      const eventPayload={occurredAt:nowIso,approvedBy:selfImmediate?me.name:null,resolution:{id:resolutionId,resolutionNo,resolutionType:type,fiscalYear:year,resolutionDate:date,title,department,project,counterparty,accountCode,settlementAccountCode:settlement,amount,taxAmount:parseMoney(payload.taxAmount),paymentMethod:payment||null,memo:memo||null,vendorId:clean(payload.vendorId,80)||null,contractId:clean(payload.contractId,80)||null,budgetExceptionId:approvedBudgetException?.id||null,documentId,status:selfImmediate?'approved':'approval_pending',createdByUserId:me.id,createdByName:me.name,createdAt:nowIso},dimensions:{...dimensions,sourceCategory:clean(payload.sourceCategory,60)}};
      const statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO documents (id,doc_type,category,title,summary,body,attachments_note,drafter,drafter_user_id,drafter_position,reviewer_user_id,reviewer_name,reviewer_position,approver_user_id,approver_name,approver_position,department,recipient,via,approval_track,approval_mode,status,template_id,template_name,form_data_json,access_scope,submitted_at,completed_at,created_at,updated_at) VALUES (?, '기안','예산·결산·사업계획·사업실적 관련 문서',?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL,NULL,'이사장결재','결재',?,NULL,?,?, '관련자',?,?,?,?)`).bind(documentId,`[${typeLabel}] ${title}`,`${resolutionNo} · ${amount.toLocaleString('ko-KR')}원`,body,'',me.name,me.id,me.position||null,reviewerIds[0]||null,reviewerIds[0]?userMap.get(reviewerIds[0])?.name:null,reviewerIds[0]?userMap.get(reviewerIds[0])?.position:null,approver.id,approver.name,approver.position,department,status,`${typeLabel}서`,JSON.stringify(formData),nowIso,selfImmediate?nowIso:null,nowIso,nowIso)];
      lines.forEach((line,index)=>statements.push(env.DB.prepare(`INSERT INTO document_approval_lines (id,document_id,line_order,line_type,user_id,user_name,user_position,status,acted_at,memo,created_at) VALUES (?,?,?,?,?,?,?,?,?,NULL,?)`).bind(`AL-${randomHex(20)}`,documentId,index+1,line.lineType,line.userId,line.userName,line.userPosition,selfImmediate?'완료':index===0?'대기':'예정',selfImmediate?nowIso:null,nowIso)));
      statements.push(env.DB.prepare(`INSERT INTO document_approvals (id,document_id,action,approver_name,approver_role,memo,created_at) VALUES (?,?, '상신',?,?,?,?)`).bind(`AP-${randomHex(20)}`,documentId,me.name,me.position||'기안자',selfImmediate?'기안자와 결재자가 동일하여 즉시 승인':'회계결의 상신',nowIso));if(selfImmediate)statements.push(env.DB.prepare(`INSERT INTO document_approvals (id,document_id,action,approver_name,approver_role,memo,created_at) VALUES (?,?, '승인',?,?,?,?)`).bind(`AP-${randomHex(20)}`,documentId,me.name,me.position||'결재자','기안자와 결재자가 동일하여 자동 승인',nowIso));statements.push(accountingEventStatement(env.DB,'resolution.create',documentId,eventPayload,`resolution.create:${documentId}`,nowIso));await env.DB.batch(statements);
      if(approvedBudgetException)await db.prepare(`UPDATE accounting_budget_change_requests SET consumed_by_resolution_id=?,consumed_at=?,updated_at=? WHERE id=? AND consumed_by_resolution_id IS NULL`).bind(resolutionId,nowIso,nowIso,approvedBudgetException.id).run();
      const sync=await processAccountingOutbox(env.DB,db,{limit:20,ignoreSchedule:true});const synced=sync.failed===0;return json({ok:true,id:resolutionId,resolutionNo,documentId,status:selfImmediate&&synced?'posted':'approval_pending',integrationPending:!synced,message:!synced?'결의서는 상신되었으나 회계 DB 연계가 대기 중입니다. 관리자 재처리로 자동 복구할 수 있습니다.':selfImmediate?'결의서가 즉시 승인되어 전표가 생성되었습니다.':'결의서가 전자결재로 상신되었습니다.'});
    }
    if(action==='create-manual-journal'){
      if(!manager)return json({ok:false,message:'수동전표 입력 권한이 없습니다.'},403);const date=clean(payload.journalDate,10);if(!validDate(date))return json({ok:false,message:'전표일자를 확인해 주세요.'},400);if(await isPeriodClosed(db,date))return json({ok:false,message:'해당 회계기간은 마감되었습니다.'},400);const rawLines=Array.isArray(payload.lines)?payload.lines as Array<Record<string,unknown>>:[],lines=rawLines.slice(0,30).map((l)=>({accountCode:clean(l.accountCode,20),debit:parseMoney(l.debit),credit:parseMoney(l.credit),department:normalizeDepartmentValue(l.department, me.position || ''),project:clean(l.project,100),counterparty:clean(l.counterparty,120),memo:clean(l.memo,300)})).filter((l)=>l.accountCode&&(l.debit||l.credit));const debit=lines.reduce((s,l)=>s+l.debit,0),credit=lines.reduce((s,l)=>s+l.credit,0);if(lines.length<2||debit<=0||debit!==credit||lines.some((l)=>l.debit<0||l.credit<0||(l.debit&&l.credit)))return json({ok:false,message:'차변과 대변을 각각 0원 이상으로 입력하고 합계가 일치하도록 작성해 주세요.'},400);const uniqueAccounts=[...new Set(lines.map((l)=>l.accountCode))],validAccounts=await db.prepare(`SELECT code FROM accounting_accounts WHERE active=1 AND code IN (${uniqueAccounts.map(()=>'?').join(',')})`).bind(...uniqueAccounts).all<{code:string}>();if((validAccounts.results||[]).length!==uniqueAccounts.length)return json({ok:false,message:'사용할 수 없는 계정과목이 포함되어 있습니다.'},400);const dimensions=await validateDimensions(db,payload),year=Number(date.slice(0,4)),id=`JRN-${randomHex(24)}`,journalNo=await nextAccountingNumber(db,'journal',year),now=new Date().toISOString();const statements:D1PreparedStatement[]=[db.prepare(`INSERT INTO accounting_journals (id,journal_no,fiscal_year,journal_date,source_type,description,status,created_by,approved_by,created_at) VALUES (?,?,?,?, 'manual',?,'posted',?,?,?)`).bind(id,journalNo,year,date,clean(payload.description,300)||'수동전표',me.name,me.name,now)];lines.forEach((l,i)=>{const lineId=`JL-${randomHex(20)}`;statements.push(db.prepare(`INSERT INTO accounting_journal_lines (id,journal_id,line_no,account_code,debit,credit,department,project,counterparty,memo) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(lineId,id,i+1,l.accountCode,l.debit,l.credit,l.department,l.project,l.counterparty,l.memo||null),db.prepare(`INSERT INTO accounting_journal_line_dimensions (journal_line_id,book_type_code,entity_id,fund_id,created_at) VALUES (?,?,?,?,?)`).bind(lineId,dimensions.bookTypeCode,dimensions.entityId,dimensions.fundId,now),monthlySummaryStatement(db,date,l,dimensions,now))});statements.push(auditStatement(db,'post','journal',id,me.id,me.name,{journalNo,debit,lines:lines.length},now));await db.batch(statements);return json({ok:true,id,journalNo,message:'수동전표를 등록했습니다.'});
    }
    if(action==='reverse-journal'){
      if(!manager)return json({ok:false,message:'전표 취소 권한이 없습니다.'},403);const sourceId=clean(payload.id,80),source=await db.prepare(`SELECT * FROM accounting_journals WHERE id=? AND status='posted'`).bind(sourceId).first<any>();if(!source)return json({ok:false,message:'취소할 전표를 찾을 수 없습니다.'},404);if(source.source_type==='reversal')return json({ok:false,message:'역분개 전표는 다시 취소할 수 없습니다. 원전표와 함께 회계담당자가 확인해 주세요.'},400);if(await isPeriodClosed(db,source.journal_date))return json({ok:false,message:'마감된 회계기간의 전표는 취소할 수 없습니다.'},400);const lines=await db.prepare(`SELECT l.*,COALESCE(d.book_type_code,'general') AS book_type_code,COALESCE(d.entity_id,'ENTITY-HQ') AS entity_id,COALESCE(d.fund_id,'') AS fund_id FROM accounting_journal_lines l LEFT JOIN accounting_journal_line_dimensions d ON d.journal_line_id=l.id WHERE l.journal_id=? ORDER BY l.line_no`).bind(sourceId).all<any>(),id=`JRN-${randomHex(24)}`,no=await nextAccountingNumber(db,'journal',source.fiscal_year),now=new Date().toISOString();const statements:D1PreparedStatement[]=[db.prepare(`INSERT INTO accounting_journals (id,journal_no,fiscal_year,journal_date,source_type,source_id,description,status,reversed_journal_id,created_by,approved_by,created_at) VALUES (?,?,?,?, 'reversal',?,?, 'posted',?,?,?,?)`).bind(id,no,source.fiscal_year,source.journal_date,sourceId,`[취소] ${source.description}`,sourceId,me.name,me.name,now),db.prepare(`UPDATE accounting_journals SET status='reversed',reversed_journal_id=? WHERE id=?`).bind(id,sourceId)];(lines.results||[]).forEach((l:any,i:number)=>{const lineId=`JL-${randomHex(20)}`,dims={bookTypeCode:l.book_type_code,entityId:l.entity_id,fundId:l.fund_id},line={accountCode:l.account_code,debit:l.credit,credit:l.debit,department:l.department,project:l.project};statements.push(db.prepare(`INSERT INTO accounting_journal_lines (id,journal_id,line_no,account_code,debit,credit,department,project,counterparty,memo) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(lineId,id,i+1,l.account_code,l.credit,l.debit,l.department,l.project,l.counterparty,`원전표 ${source.journal_no} 취소`),db.prepare(`INSERT INTO accounting_journal_line_dimensions (journal_line_id,book_type_code,entity_id,fund_id,created_at) VALUES (?,?,?,?,?)`).bind(lineId,l.book_type_code,l.entity_id,l.fund_id,now),monthlySummaryStatement(db,source.journal_date,line,dims,now))});if(source.source_type==='resolution'&&source.source_id)statements.push(db.prepare(`UPDATE accounting_resolutions SET status='cancelled',updated_at=? WHERE id=?`).bind(now,source.source_id));statements.push(auditStatement(db,'reverse','journal',sourceId,me.id,me.name,{reversalNo:no},now));await db.batch(statements);return json({ok:true,message:'원전표를 삭제하지 않고 역분개 전표로 취소했습니다.',reversalNo:no});
    }
    if(action==='close-period'||action==='reopen-period'){
      if(!manager)return json({ok:false,message:'회계기간 마감 권한이 없습니다.'},403);const year=Number(payload.year),month=Number(payload.month);if(!Number.isInteger(year)||month<1||month>12)return json({ok:false,message:'마감 연월을 확인해 주세요.'},400);const now=new Date().toISOString(),id=`CLS-${year}-${String(month).padStart(2,'0')}`;if(action==='close-period'){
        const blockers=await getReconciliationBlockers(db,year,month);
        if(blockers.unmatched||blockers.incomplete)return json({ok:false,message:`거래 대사가 완료되지 않아 마감할 수 없습니다. 미대사 ${blockers.unmatched}건, 미확정 대사계좌 ${blockers.incomplete}개를 먼저 처리해 주세요.`,reconciliationRequired:true,...blockers},400);
        const imbalance=await db.prepare(`SELECT COALESCE(SUM(debit_total),0) AS d,COALESCE(SUM(credit_total),0) AS c FROM accounting_monthly_summary WHERE fiscal_year=? AND period_month=?`).bind(year,month).first<{d:number;c:number}>();if(Number(imbalance?.d||0)!==Number(imbalance?.c||0))return json({ok:false,message:'차변·대변 합계가 일치하지 않아 마감할 수 없습니다.'},400);await db.batch([db.prepare(`INSERT INTO accounting_closings (id,fiscal_year,period_month,status,closed_by,closed_at,memo) VALUES (?,?,?,'closed',?,?,?) ON CONFLICT(fiscal_year,period_month) DO UPDATE SET status='closed',closed_by=excluded.closed_by,closed_at=excluded.closed_at,memo=excluded.memo`).bind(id,year,month,me.name,now,clean(payload.memo,500)||null),auditStatement(db,'close','period',id,me.id,me.name,{year,month,...blockers},now)]);return json({ok:true,message:`${year}년 ${month}월 회계기간을 마감했습니다.`})}await db.batch([db.prepare(`DELETE FROM accounting_closings WHERE fiscal_year=? AND period_month=?`).bind(year,month),auditStatement(db,'reopen','period',id,me.id,me.name,{year,month},now)]);return json({ok:true,message:`${year}년 ${month}월 마감을 해제했습니다.`});
    }
    if(action==='retry-integration'){
      if(!manager)return json({ok:false,message:'회계연계 재처리 권한이 없습니다.'},403);
      const result=await processAccountingOutbox(env.DB,db,{limit:50,ignoreSchedule:true});
      return json({ok:true,...result,hasFailures:result.failed>0,message:result.failed?`${result.processed}건 처리, ${result.failed}건은 아직 실패 상태입니다. 오류 원인을 확인한 뒤 다시 재처리해 주세요.`:`${result.processed}건의 회계연계를 처리했습니다.`});
    }
    return json({ok:false,message:'지원하지 않는 회계 처리입니다.'},400);
  }catch(error){console.error('accounting action failed',action,error);return json({ok:false,message:error instanceof Error?error.message:'회계 처리 중 오류가 발생했습니다.'},500)}
};
export const onRequestGet:PagesFunction=async()=>json({ok:false,message:'POST 방식으로 요청해 주세요.'},405);
